### ISSUE TITLE
Zwischenpräsentation vorbereiten

### ISSUE THREAD

**Issue by JeannineB** [Stonks2Moon/Orga#1]
Folien bis 18. März vorbereiten - bis 23. März änderbar 

--> nächste Woche längeres Anfangsmeeting, Folien besprechen
--> gerne mit weiteren Gruppenmitglieder

**Comment by jangruebener** [comment]
Unsere Zwischenpräsentation wird in folgendem Issue bis zur nächsten Vorlesung getrackt und verfollständigt:

https://github.com/Stonks2Moon/Simulation/issues/22

**Comment by JanZecevic** [comment]
Die Zwischenpräsentation der Privatkundenbroker findet sich im folgendem Issue:
[Zwischenpräsentation anlegen #4](https://github.com/Stonks2Moon/Privatkundenbroker-Allgemein/issues/4)
