### ISSUE TITLE
Absprache: Wie gestalten wir die Abschlusspräsentation

### ISSUE THREAD

**Issue by jangruebener** [Stonks2Moon/Orga#7]
Um falsche Darstellungen der Folien wie bei der Zwischenpräsentation zu vermeiden sollten wir uns mal austauschen welche anderen Möglichkeiten wir haben. pptx als pdf? Wie sieht es mit Screen Share aus um die Frontends oder ähnliches zu zeigen

**Comment by JeannineB** [comment]
Soweit ich mich erinnere haben wir gesagt, dass wir diese Mal keine Gesamt-Präsi machen, sondern jede Gruppe eine eigene (mithilfe der Vorlage). Somit wäre es dann eure Sache, ob ihr diese als PDF exportiert, eine Bildschirmübertragung macht oder eine .pptx hochladet. Aber an sich wäre es dann besser aus jeder Gruppe einen Präsentator zu bestimmen, der dann eben seinen Bildschirm / die Präsentation teilt.
