### ISSUE TITLE
Arbeitsstunden - geschätzt und wirklich weiterleiten 

### ISSUE THREAD

**Issue by JeannineB** [Stonks2Moon/Orga#8]

**Comment by JanZecevic** [comment]
Privatkundenbroker:
- Geschätzt: 148 h
- Tatsächlich 159 h

**Comment by jangruebener** [comment]
Simulation:

- Geschätzt: 555
- Tatsächlich: 437

**Comment by aalenaa** [comment]
Geschäftskundenbroker: 

- Geschätzt: 347 h
- Tatsächlich: 427 h
